steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/nest-hello-world', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/nest-hello-world']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'nest-hello-world', '--image', 'gcr.io/$PROJECT_ID/nest-hello-world', '--region', 'us-central1']
images:
- gcr.io/$PROJECT_ID/[nest-hello-world]